version: '3'
services:
    neo4j:
        image: neo4j:3.5
        ports:
            - 7474:7474
            - 6477:6477
            - 7687:7687
        volumes:
            - $GRAPH_DATA_DIR:/data_in
            - neo4j-data:/data
        environment:
            - NEO4J_AUTH=none

volumes:
    neo4j-data:
