GRAPH_DB = 'bolt://localhost:7687'
RETRIEVER_PATH = 'retriever'

READER_ARCHITECTURE = 'albert'
READER_PATH = 'reader'

REASONER_ARCHITECTURE = 'bert-base-uncased'
REASONER_PATH = 'reasoner'
REASONER_NUM_REASONING_STEPS = 2
REASONER_MAX_PARAGRAPH_NUM = 10
REASONER_MAX_SEQ_LEN = 256
