# DEFAULTS
DEFAULT_LANGUAGE = 'english'

# VARIABLE NAMES
GRAPH_QA_API_CONFIG_PATH = 'GRAPH_QA_API_CONFIG_PATH'
GRAPH_DB = 'GRAPH_DB'
RETRIEVER_PATH = 'RETRIEVER_PATH'

READER_ARCHITECTURE = 'READER_ARCHITECTURE'
READER_PATH = 'READER_PATH'
