# DEFAULTS
DEFAULT_LANGUAGE = 'english'

# VARIABLE NAMES
GRAPH_QA_API_CONFIG_PATH = 'GRAPH_QA_API_CONFIG_PATH'
GRAPH_DB = 'GRAPH_DB'
RETRIEVER_PATH = 'RETRIEVER_PATH'

REASONER_PATH = 'REASONER_PATH'
REASONER_NUM_REASONING_STEPS = 2
REASONER_MAX_PARAGRAPH_NUM = 10
REASONER_MAX_SEQ_LEN = 256

READER_ARCHITECTURE = 'READER_ARCHITECTURE'
READER_PATH = 'READER_PATH'
