# DEFAULTS
DEFAULT_LANGUAGE = 'english'

# VARIABLE NAMES
GRAPH_QA_API_CONFIG_PATH = 'GRAPH_QA_API_CONFIG_PATH'

RETRIEVER_ELASTICSEARCH_ADDR = 'RETRIEVER_ELASTICSEARCH_ADDR'
RETRIEVER_ELASTICSEARCH_INDEX = 'RETRIEVER_ELASTICSEARCH_INDEX'
RETRIEVER_GRAPH_DB = 'GRAPH_DB'
RETRIEVER_PATH = 'RETRIEVER_PATH'

REASONER_ARCHITECTURE = 'REASONER_ARCHITECTURE'
REASONER_PATH = 'REASONER_PATH'
REASONER_NUM_REASONING_STEPS = 'REASONER_NUM_REASONING_STEPS'
REASONER_MAX_PARAGRAPH_NUM = 'REASONER_MAX_PARAGRAPH_NUM'
REASONER_MAX_SEQ_LEN = 'REASONER_MAX_SEQ_LEN'

READER_ARCHITECTURE = 'READER_ARCHITECTURE'
READER_PATH = 'READER_PATH'
