GRAPH_DB = ''
RETRIEVER_PATH = ''

REASONER_ARCHITECTURE = ''
REASONER_PATH = ''
REASONER_NUM_REASONING_STEPS = None
REASONER_MAX_PARAGRAPH_NUM = None
REASONER_MAX_SEQ_LEN = None

READER_ARCHITECTURE = ''
READER_PATH = ''
